[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"
            Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=2592000"
     X-Content-Type-Options = "nosniff"
            X-Frame-Options = "DENY"
           X-XSS-Protection = "1; mode=block"
